// docs/clover-architecture.md §4.2 `payments`. No delete endpoint is ever built for this
// table by design — only a status change to 'voided' (§0: void authorization is Management
// + Admin). or_number is required and typed in from the clinic's pre-printed manual OR
// booklet, not generated by the system (§0/§6 — avoids a BIR CAS/POS accreditation project).
exports.up = function up(knex) {
  return knex.schema.createTable('payments', (table) => {
    table.increments('id').primary();
    table
      .integer('billing_statement_id')
      .notNullable()
      .references('id')
      .inTable('billing_statements')
      .onDelete('RESTRICT');

    table.decimal('amount_paid', 10, 2).notNullable();
    table.string('payment_method', 50).notNullable();
    table.string('or_number', 50).notNullable();

    table
      .integer('received_by')
      .notNullable()
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT');
    table.timestamp('paid_at').notNullable().defaultTo(knex.fn.now());

    table.string('status', 20).notNullable().defaultTo('active'); // active | voided
    table.text('void_reason');
    table
      .integer('voided_by')
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT');
    table.timestamp('voided_at');

    table.index(['billing_statement_id']);
  });
};

exports.down = function down(knex) {
  return knex.schema.dropTableIfExists('payments');
};
